export const PayletterPGCode = {
  creditcard: 'creditcard',
  banktransfer: 'banktransfer',
  virtualaccount: 'virtualaccount',
  mobile: 'mobile',
  voucher: 'voucher',
  book: 'book',
  culture: 'culture',
  smartculture: 'smartculture',
  happymoney: 'happymoney',
  mobilepop: 'mobilepop',
  teencash: 'teencash',
  tmoney: 'tmoney',
  cvs: 'cvs',
  eggmoney: 'eggmoney',
  oncash: 'oncash',
  phonebill: 'phonebill',
  cashbee: 'cashbee',
  kakaopay: 'kakaopay',
  payco: 'payco',
  checkpay: 'checkpay',
  toss: 'toss',
  ssgpay: 'ssgpay',
  naverpay: 'naverpay',
  samsungpay: 'samsungpay',
  applepay: 'applepay',
} as const;

export type PayletterPGCode =
  (typeof PayletterPGCode)[keyof typeof PayletterPGCode];
